insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1000,'Sarnia, ON','Canada','YZR',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1002,'Canberra, A.C.T.','Australia','CBR',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1004,'Szczecin','Poland','SZZ',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1006,'Nakhon Si Thammarat','Thailand','NST',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1008,'Varanasi','India','VNS',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1010,'Seville','Spain','SVQ',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1012,'Binghamton, NY','USA','BGM',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1014,'Busan, Korea','Republic of','PUS',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1016,'Abu Dhabi','United Arab Emirates','AUH',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1018,'Tallahassee, FL','USA','TLH',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1020,'Reykjavik','Iceland','REK - All Airports',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1022,'Cali','Colombia','CLO',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1024,'Sandefjord','Norway','TRF',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1026,'Larnaca','Cyprus','LCA',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1028,'Vancouver, BC','Canada','YVR',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1030,'Copenhagen','Denmark','CPH',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1032,'Basel','Switzerland','BSL',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1034,'Gaspe, PQ','Canada','YGP',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1036,'Milan','Italy','MIL - All',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1038,'Medicine Hat, AB','Canada','YXH',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1040,'Naryan Mar','Russia','NNM',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1042,'Decatur, IL','USA','DEC',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1044,'Puerto Vallarta','Mexico','PVR',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1046,'Barranquilla','Colombia','BAQ',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1048,'Ponca City, OK','USA','PNC',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1050,'Quesnel, BC','Canada','YQZ',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1052,'Mulhouse','France','MLH',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1054,'Kailua-Kona, HI','USA','KOA',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1056,'Concepcion','Chile','CCP',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1058,'Dangriga','Belize','DGA',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1060,'Cairns, Qld.','Australia','CNS',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1062,'Charlottesville, VA','USA','CHO',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1064,'Monclova','Mexico','LOV',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1066,'Tampico','Mexico','TAM',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1068,'Cape Town','South Africa','CPT',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1070,'Osorno','Chile','ZOS',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1072,'Agana','Guam','GUM',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1074,'Manama','Bahrain','BAH',0);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1076,'Santiago','Dominican Republic','STI',1);
insert into Lotnisko(IdLotniska,NazwaLotniska,Kraj,SkrotLotniska,CzyObslugujeRejsowe) values (1078,'Smithers, BC','Canada','YYD',0);
